server:
  port: 8081

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8088/user
      
#spring:
 # config:
  #  import: "optional:configserver:"
#Para resolver o erro foi adicionada a dependencia:
#<dependency>
    #<groupId>org.springframework.cloud</groupId>
    #<artifactId>spring-cloud-starter-bootstrap</artifactId>
#</dependency>
