
#spring:
 # application:
  #  name: loja
  #config:
    #import: "optional:configserver:"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8088/user

# Compartilhar contexto de seguranca (Token)      
hystrix:
  shareSecurityContext: true
